#+TITLE: Boot Starp
* Bootstrap 简介:
来自 Twitter，是目前很受欢迎的前端框架，BootStrap 是给予 HTML，CSS，JS 的，简介灵活。基于 HTML5 和 CSS3 开发的。让页面更美观，编写更快捷，更偏向于 CSS，就像 Jquery 与 JS。本质上是 CSS 框架。
** 包含：
1. 组件：包含了丰富的 web 组件，包括下拉菜单，按钮组等等
2. JS 插件
3. 框架代码
4. Bootstrap less：Less 语言对 CSS 深度预处理。
** 特性
1. 预处理脚本： less 和 sass 开发
2. 一个框架，多种设备
3. 特性齐全
4. 完全开源
** 官网地址
1. [[getbootstrp.com]] 官网
2. [[www.bootcss.com]] 中文网
提供下载和网站实例精选
#+begin_src example
<!-- 最新版本的 Bootstrap 核心 CSS 文件 -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">

<!-- 可选的 Bootstrap 主题文件（一般不用引入） -->
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap-theme.min.css" integrity="sha384-rHyoN1iRsVXV4nD0JutlnGaslCJuC7uwjduW9SVrLvRYooPp2bWYgmgJQIXwl/Sp" crossorigin="anonymous">

<!-- 最新的 Bootstrap 核心 JavaScript 文件 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

#+end_src example
如上第三条，一定要在 JQuery 再导入，一般下载再操作而不是导入链接。
** 预编译版本
bootstrap - css - bootstrap.css 非压缩版，带 min 的是压缩版
* 基本使用
** 基本模版
#+begin_src html :results output
<!DOCTYPE html>
<html lang="zh-CN">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>Bootstrap Ex1</title>

    <!-- Bootstrap -->
    <link href="bootstrap-3.3.7-dist/css/bootstrap.min.css" rel="stylesheet">
        <!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
    <script src="jquery-3.5.1.js"></script>
    <!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
    <script src="bootstrap-3.3.7-dist/js/bootstrap.min.js"></script>

  </head>
  <body>
    <h1>你好，世界！</h1>


  </body>
</html>

#+end_src
由于自动会为不同的屏幕生成响应式布局，禁止响应式布局的方法有
1. 移除 viewport 这一段<meta>代码
2. 通过为.container 类设置一个 width 值
   ...
** 全局 CSS 样式
*** 概览
1. HTML5 文档类型，页面文档需要定义为 HTML5 文档
   #+begin_src html
<!DOCTYPE html>
<html lang="zh-CN">
  ...
   #+end_src
2.  =<meta name="viewport" content="width=device-width, initial-scale=1">=
   定义自适应窗口，一般不修改
3. 排版和链接：
   为 body 元素设定了背景颜色#fff;纯白
   链接处于 hover 状态下才使用下划线
4. 布局容器：需要为页面内容和栅格系统包裹一个.container 容器
   #+begin_src js
<div class="container"></div>
   #+end_src
   .container 指代一个类的名字
** 栅格系统
系统会自动分为 12 列，包含了预定义的类
1. .col-xs- 类前缀，超小屏幕的手机
2. .col-sm- 平板
3. .col-md- 中等屏幕
4. .col-lg- 大屏幕
首先需要包含在容器中
#+begin_src html
<div class="row">
  <div class="col-md-1">.col-md-1</div>
  <div class="col-md-1">.col-md-1</div>
  <div class="col-md-1">.col-md-1</div>
  <div class="col-md-1">.col-md-1</div>
  <div class="col-md-1">.col-md-1</div>
  <div class="col-md-1">.col-md-1</div>
  <div class="col-md-1">.col-md-1</div>
  <div class="col-md-1">.col-md-1</div>
  <div class="col-md-1">.col-md-1</div>
  <div class="col-md-1">.col-md-1</div>
  <div class="col-md-1">.col-md-1</div>
  <div class="col-md-1">.col-md-1</div>
</div>
<div class="row">
  <div class="col-md-8">.col-md-8</div>
  <div class="col-md-4">.col-md-4</div>
</div>
<div class="row">
  <div class="col-md-4">.col-md-4</div>
  <div class="col-md-4">.col-md-4</div>
  <div class="col-md-4">.col-md-4</div>
</div>
<div class="row">
  <div class="col-md-6">.col-md-6</div>
  <div class="col-md-6">.col-md-6</div>
</div>
#+end_src
[[https://v3.bootcss.com/css/]]

*** 切换工作情况
=<div class="col-md-1 col-xs-6">.col-md-1</div>=
手机使用时候和屏幕使用时候切换
*** 列偏移
offsite
=<div class="col-md-8 col-md-offset-2">= 即左边偏移两个位置
*** 嵌套
#+begin_src html
<div class='col-md-1">
   <div class='row'>
     <div class = 'col-md-4'>.col-md-1/9</div>
...
#+end_src
** 排版
#+begin_src html
<div class="container">
  <h1>hello world</h1>
  <h2>hello world</h2>
  <p>hello world<span class="h1">hello</span></p>
  <h3>hello world</h3>
</div>
#+end_src

*** 通过<small></small> 嵌套副标题
*** 页面主题
全局 font-size 设置为 14px, inline-height 设置为 1.428。这些属性直接赋予给了<body>元素和所有段落元素。另外<p>元素还被设置了等于 1/2 行高,即 10px 的底部外边距
*** 中心内容，让段落突出显示
=<p class="lead>...</p>=
*** 内联文本元素
<mark></mark>可以让文本高亮
*** 被删除的文本
<del></del>标签可以
*** 无用文本
<s> </s>
*** 插入文本
<ins> </ins>
*** 带下划线的文本
<u></u>
*** 着重
<strong></strong>
*** 斜体
<em> </em>
*** 对齐
1. =<p class="text-left">Left aligned text.</p>A=
2. text-center
3. text-right
4. text-justify
5. text-nowrap
*** 改变文本的大小写
1. class="text-lowercase"
2. class="text-uppercase"
3. class="text-caplitalize"
*** 缩略语
1. <abbr title="attribute">attr</attr>
2. 首字母缩略语
   =<abbr title="HyperText Markup Language" class="initialism">HTML</abbr>=
*** 地址
让联系信息以最接近日常使用的格式呈现。在每行结尾添加<br>可以保留需要的样式。用<address></address>封装起来
*** 引用
将任何 HTML 元素包裹在<blockquote>中即可表现为引用样式。对于直接引用，建议用<p>标签.
*** 多种引用样式
*** 列表：同 HTML 原生列表
*** 代码
通过<code>标签包裹内联样式的代码片段
=<code>&lt;section&gt;</code> should be wrapped as inline=
*** 用户输入<kbd>
#+begin_src html
to switch directories, type <kbd>cd</kbd> followed by the name of the directory.<br>
to edit settings, press<kbd><kbd>ctrl</kbd>+<kbd>,</kbd></kbd>
#+end_src
*** /代码块/
<pre></pre>标签
#+begin_src
<pre>&lt;p&gt;Sample text here...&lt;/p&gtl</pre>
#+end_src
*** 变量
<var></var>
*** 程序输出...
*** 表格
=<table class="table">=
... 有多种样式 table-striped, table-boardered
*** 鼠标悬停
*** 状态类
